name: Git Actions Demo
on: [ pull_request ]
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: node JsCodingChallenge.js
      #- run: node Js_Challenge\jsCodeChallenge2.js
      #- run: node Js_Challenge\jsCodeChallenge3.js
      #- run: node Js_Challenge\jsCodeChallenge4.js
      #- run: node Js_Challenge\jsCodeChallenge5.js
      #- run: node Js_Challenge\jsCodeChallenge6.js
      #- run: node Js_Challenge\jsCodeChallenge7.js
      #- run: node Js_Challenge\jsCodeChallenge8.js
      #- run: node Js_Challenge\jsCodeChallenge9.js
      #- run: node Js_Challenge\jsCodeChallenge10.js
      # - run: python3 python_Task\task1.py
      #- run: python3 python_Task\task2.py
      #- run: python3 python_Task\task3.py
      #- run: python3 python_Task\task4.py
      #- run: python3 python_Task\task5.py
      #- run: python3 python_Task\task6.py
      #- run: python3 python_Task\task7.py
      #- run: python3 python_Task\task8.py
      #- run: python3 python_Task\task9.py
      #- run: python3 python_Task\task10.py
      #- run: python3 python_Task\task11.py
      #- run: python3 python_Task\task12.py
      #- run: python3 python_Task\task13.py || true
      #- run: python3 python_Task\task14.py
      #- run: python3 python_Task\task15.py
      #- run: python3 python_Task\task16.py
      #- run: python3 python_Task\task17.py
      #- run: python3 python_Task\task18.py
      #- run: python3 python_Task\task19.py
      #- run: python3 python_Task\task20.py
      #- run: python3 python_Task\task21.py
      #- run: python3 python_Task\task22.py
      #- run: python3 python_Task\task23.py
      #- run: python3 python_Task\task24.py
      #- run: python3 python_Task\task25.py
     